Repository CESARBR/knot-virtualthing, pull requests merged in 2020-07, with the labels that each got.

#9 Fix valid bit offset function working principle
  src/properties.c
Labels: Priority: medium, bug

#10 Log when fail to load device properties
  src/properties.c
Labels: Priority: low, enhancement

#11 Fix key value when lookup data item hashmap
  src/device.c
  src/device.h
  src/properties.c
Labels: Priority: high, bug
